### ISSUE TITLE
OSError nerdstash_v1.model": No such file or directory Error #2

### ISSUE THREAD

**Issue by TimmekHW** [LlmKira/novelai-python#60]
```
Traceback (most recent call last):
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\Альоша\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Альоша\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Альоша\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Альоша\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path    
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\Альоша\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Альоша\.vscode\extensions\ms-python.debugpy-2024.4.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code   
    exec(code, run_globals)
  File "C:\stable-diffusion-webui\outpust\OneDrive - iicx\sd_nai_ref\work_copy_server\sd_bot_1_6_4.py", line 29, in <module>
    from danboorutags_1_7 import cmd_dan, cmd_tt, cmd_tags, cmd_deep, sfw_prompt_generator, nsfw_prompt_generator
  File "C:\stable-diffusion-webui\outpust\OneDrive - iicx\sd_nai_ref\work_copy_server\danboorutags_1_7.py", line 20, in <module>
    from novelai_python.tool.random_prompt import RandomPromptGenerator
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\novelai_python\__init__.py", line 14, in <module>
    from .sdk import GenerateImageInfer, ImageGenerateResp
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\novelai_python\sdk\__init__.py", line 7, in <module>
    from .ai.generate import LLM, LLMResp  # noqa 401
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\novelai_python\sdk\ai\generate\__init__.py", line 19, in <module>
    from ...._response.ai.generate import LLMResp
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\novelai_python\_response\ai\generate.py", line 6, in <module>
    from novelai_python.tokenizer import LLMTokenizer
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\novelai_python\tokenizer\__init__.py", line 121, in <module>
    class LLMTokenizer:
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\novelai_python\tokenizer\__init__.py", line 139, in LLMTokenizer
    _NERDSTASH_TOKENIZER_v1 = SentencePiece(_NERDSTASH_TOKENIZER_v1_PATH)
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\novelai_python\tokenizer\__init__.py", line 31, in __init__
    self.Load(model_path)
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 961, in Load
    return self.LoadFromFile(model_file)
  File "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\sentencepiece\__init__.py", line 316, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
OSError: Not found: "c:\Users\Альоша\AppData\Local\Programs\Python\Python310\lib\site-packages\novelai_python\tokenizer\nerdstash_v1.model": No such file or directory Error #2 

but I have this file!
![image](https://github.com/LlmKira/novelai-python/assets/94626112/b999f4a4-8ed0-45e0-ae47-2b720271f960)
```

**Comment by sudoskys** [comment]
i will check it

**Comment by sudoskys** [comment]
Because your hostname is in Russian, it won't load. I've canceled the initial model loading process. You can now use interfaces outside of LLM.

**Comment by TimmekHW** [comment]
> Because your hostname is in Russian, it won't load. I've canceled the initial model loading process. You can now use interfaces outside of LLM.
> 
> new version was published, `pip install -U novelai-python`
> 
> If any problem occurs, please reopen this thread

Thank you very much, it helped.However, I had to completely delete the library and install it again because ``pip install -U novelai-python`` did not help
